### ISSUE TITLE
Option to remove the X-Requested-With

### ISSUE THREAD

**Issue by jawadst** [franciscop/umbrella#105]
Hi there!

Would it be possible to add an option to not add the "X-Requested-With" header to XMLHttpRequest objects?

I don't need my requests to be authorized (I don't need cookies or anything) and that header is triggering a pre-flight OPTIONS request that does not work in my use case.
I don't think there is any way to prevent Umbrella from adding that header and it cannot be removed in a `before` callback as there is no option on the `XMLHttpRequest` object to do so.

The option could also avoid doing `withCredentials = true` (at least that's reversible in a `before` callback).

Jawad

**Comment by franciscop** [comment]
I highly recommend using `fetch()` nowadays that browsers support it (and since it can be polyfilled). The whole AJAX part from Umbrella could be easily removed and with the modern APIs no one would even notice.

The header is there for [security reasons](https://stackoverflow.com/a/22533680/938236), and if that part of the code was to be changed it'd be to be deprecated/removed, not to be made more complex.

**Comment by jawadst** [comment]
Thanks for the answer. I understand your point although I cannot use fetch/polyfills in my current environment so I'll find an alternative.

**Comment by franciscop** [comment]
The method `ajax()` is being deprecated for the standard `fetch()`. Please see the relevant issue and let me know if you have anything against it: httpsthub.com/franciscop/umbrella/issues/124
