### ISSUE TITLE
Appending a row to a tbody

### ISSUE THREAD

**Issue by bramton** [franciscop/umbrella#117]
I am trying to append a row to a table. Instead of adding a new row directly under the `tbody` element it places the new row in a new `tbody` element. Appending an element to a list works fine. I wonder what I am doing wrong.
```html
<table>
<tbody>
  <tr>
    <td>Jonny</td>
    <td>1986</td>
  </tr>
</tbody>
</table>

<ul>
<li>one</li>
</ul>
  
<script src="umbrella.min.js"></script>
<script type="text/javascript">  
u('tbody').append("<tr><td>Eric</td><td>2001</td></tr>");
u('ul').append("<li>two</li>");
</script>
```

This is the result:
```html
<table>
<tbody>
  <tr>
    <td>Jonny</td>
    <td>1986</td>
  </tr>
  <tbody>
    <tr>
      <td>Eric</td>
      <td>2001</td>
    </tr>
  </tbody>
</tbody>
</table>

<ul>
<li>one</li>
<li>two</li>
</ul>

**Comment by franciscop** [comment]
The issue seems to come from this bit: [generate html](https://github.com/franciscop/umbrella/blob/master/src/plugins/generate/generate.js#L6). Specially, if you do this with native Javascript [(see JSFiddle)](https://jsfiddle.net/c2b1crpo/):

```js
const table = document.createElement('table');
table.innerHTML = '<tr>Hello</tr>';
document.body.innerHTML = table.children[0].nodeName;
```

I would have expected to see `TR` in the body, but instead got `TBODY`. This means that the native method is injecting the `<tbody>` in the middle which is not accounted for by umbrella.

## Quick Fix

Add this to the top of your file:

```js
// [INTERNAL USE ONLY]
// Generate a fragment of HTML. This irons out the inconsistences
u.prototype.generate = function (html) {
  // Table elements need to be child of <table> for some f***ed up reason
  if (/^\s*<t(h|r|d)/.test(html)) {
    return u(document.createElement('table')).html(html).children().children().nodes;
  } else if (/^\s*</.test(html)) {
    return u(document.createElement('div')).html(html).children().nodes;
  } else {
    return document.createTextNode(html);
  }
};
```

Notice the extra `.children()`. This should override the core library until the fix is published, thanks for the bug report :heart:
