### ISSUE TITLE
Reactive JS /  Virtual DOM functionality

### ISSUE THREAD

**Issue by prologic** [franciscop/umbrella#118]
Would you consider adding a very minimal patch/diff set of operations into this library?

I've been experimenting with [morphdom](https://github.com/prologic/go-picnic-umbrella/tree/morphdom_reactive_js) and it's not too bad.

**Comment by franciscop** [comment]
Could you explain a bit more please? But very likely virtual dom is outside the scope of this lib.

**Comment by prologic** [comment]
> But very likely virtual dom is outside the scope of this lib

So I don't mean for Umbrella JS to grow a "virtual-dom" at all. I'm thinking more about supporting something more like `morphdom(fromNode, toNode)` at a very basic level that just patches the dom to match what you want. Umbrella supports a rich set of dom functions; so why not one more :)

**Comment by franciscop** [comment]
There are many reasons why it's not a good fit, but it is definitely outside the scope of Umbrella:

> Lightweight javascript library for DOM manipulation, events and AJAX

Instead, this is roughly the scope of Umbrella:

- Lightweight (which [morphdom.js](https://github.com/prologic/go-picnic-umbrella/blob/morphdom_reactive_js/static/js/morphdom.js) is definitely not)
- jQuery-like. Does not match 100%, but if you are familiar with jQuery then Umbrella should be easy to pick up. This implies imperative and not declarative.
- Stable. Umbrella is basically "finished" (except for bug fixes), and doing morphdom is a huge, fragile task. I am not even sure it's possible (and I am not interested in trying now, have other priorities). For instance, event handlers seem impossibly difficult since the API is somewhat opaque.

You are of course free, and I've done a similar thing in some of my projects, to create your own plugin and use it for yourself or publish it in Github if you want:

```js
u.prototype.morphdom = function (from, to) {
  // ...
};
```

**Comment by prologic** [comment]
Thanks :D
