### ISSUE TITLE
Form submit not triggered

### ISSUE THREAD

**Issue by nullraum** [franciscop/umbrella#132]
Hello Francisco,

Today I tried to submit a form triggered by a changed select. Maybe I'm doing something wrong, but the form is not submitted.

It works with jquery, but not with umbrella.

It would be great if you could take a look at this codepen, which Shows the problem:

https://codepen.io/nullraum/pen/yQoqQO?editors=1111

Beside that, thank you for umbrella, its a amazing piece of work!

Regards
Noah

**Comment by franciscop** [comment]
It seems to be working perfectly fine for me, what browser are you using? You want that, when the select is changed, the form submits and logs the value, right?

**Comment by nullraum** [comment]
I tried it with Edge, Chrome and Firefox right now:

Edge - no submit
Chrome - no submit
Firefox - works!

I just want to submit the form, when a select changes.

**Comment by franciscop** [comment]
You are right, I can reproduce this issue. There seems to be no regression in the [tests](https://umbrellajs.com/tests), so this is a genuine new and untested bug report. I'll dig deeper later, thanks!

**Comment by franciscop** [comment]
Initial findings: with very native Javascript it's not working as intended as well:

```js
console.log('Sending');
document.querySelector('form').dispatchEvent(new Event('submit'));
console.log('Does not send...');

console.log('Old style');
const domEvent = document.createEvent('Event');
domEvent.initEvent('submit', false, true);
document.querySelector('form').dispatchEvent(domEvent);
console.log('Still does not send...');
```

**Comment by franciscop** [comment]
Could you please try this @nullraum?

```js
u('select').on('change keyup', function(e){
  console.log(this.value + " looks delicious");
  u(this).closest("form").first().submit();
});
```

**Comment by nullraum** [comment]
This works in Desktop-Edge and Desktop-Chrome!

**Comment by franciscop** [comment]
Sure, in that example I am using native Javascript (the `.first()` will return an element). While the event system *could* be reimplemented to be closer to jQuery, jQuery events have bigger issues:

```js
// This event is never triggered with jQuery :(
document.querySelector('form').addEventListener('submit', e => alert('Hi there!'));

$('form').submit();
```

This is because jQuery uses _syntetic_ events. This also doesn't work for instance:

```js
$('form').on('submit', e => {
	console.log('Magic');
});
$('form').forEach(function(){
  this.submit();     // Does NOT call the event listener above
  $(this).submit();  // Calls the event listener
});
```

It is a pity that the `.trigger('submit')` of Umbrella works differently in different browsers, but that is because the `.dispatchEvent()` works differently in different browsers, not because of any funny business going on on Umbrella's side.

PS, thanks for opening an issue, it seems it's a legit bug, but on the browsers side.
