### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by lamorales-xumak** [franciscop/umbrella#133]
First i wanna start saying that Umbrella JS is great, has some advantages over other FE frameworks but recently I run a benchmark where compare the frameworks: js(pure), jquery, zepto, bliss, umbrella.

To my sorprise the performance of umbrella es very low.

Someone can be check, just to be a double check.

Results
```
Vanilla Get ID	                3,097,550.0 Ops/sec
Vanilla Get Text	        2,694,215.0 Ops/sec
Vanilla Get Html	           346,918.5 Ops/sec
jQuery Get ID	                 1,271,862.0 Ops/sec
jQuery Get Text	           968,668.1 Ops/sec
jQuery Get Html	           285,206.7 Ops/sec
Zepto Get ID	                 1,271,794.0 Ops/sec
Zepto Get Text	            474,101.3 Ops/sec
Zepto Get Html	           268,258.8 Ops/sec
Bliss Get ID	                 1,265,257.0 Ops/sec
Bliss Get Text	                 1,163,978.0 Ops/sec
Bliss Get Html	                  1,172,167.0 Ops/sec
Umbrella Get ID	            237,721.2 Ops/sec
Umbrella Get Text	           240,241.9 Ops/sec
Umbrella Get HTML	   145,707.9 Ops/sec
```

Benchmark link https://www.measurethat.net/Benchmarks/Show/4274/2/performance-test-by-id-js-vs-jquery-vs-zepto-vs-bliss-v
Results link https://www.measurethat.net/Benchmarks/ShowResult/40103

**Comment by franciscop** [comment]
There were some micro optimizations before, but they were very inconsistent among browsers so I removed them.

Is the performance really slow? Is that really a bottleneck for you? When you are getting an id for instance, how does taking 0.000004 seconds (0.004ms) instead of 0.0000003 seconds (0.0003ms) affect your performance?

**Comment by franciscop** [comment]
While Umbrella *is* slower than other libraries, it is amazingly fast anyway and should definitely not affect any real-world performance.

PS, I'll leave this open until I change the text in the homepage, which is misleading now that there are no longer micro optimizations.

**Comment by NetLancer** [comment]
I think taking into consideration mobile internet accessibility (mostly outside of US and WestEurope) it should be more of the size of library downloaded rather than incredibility of performance. I think real world criterias matter

**Comment by franciscop** [comment]
@NetLancer, while I agree, in this case the library size is also negligible. It was +- 100 *bytes* of change AFAIK, which is nothing but a rounding error.

For this case, my opinion is that if library size AND performance are already working great, what should be the criteria then? It should be stability/maintainability. Which is, hands down, using the native `document.querySelectorAll()` instead of a bunch of `if` and RegExp.

**Comment by lamorales-xumak** [comment]
@franciscop You're right, the performance don't affect me, that's why I started the issue saying Umbrella JS is great.

I still prefer UmbrellaJS over the rest but it were curious the big difference.

thanks for the answers.

**Comment by mjau-mjau** [comment]
Hi Francisco, thanks for the reply and reference. You are right about the insignificant difference in selector performance. The exception being heavy loops, but in this case it would be considered bad practice to query elements inside each iteration anyway. Essentially, it seems pointless to extend u() with additional selector mechanisms.

On a side note, it's unfortunate how performance tests (like the one in this post) reflect negatively upon umbrella. One might easily conclude that the codebase of umbrella is slow, whereas in fact it is simply the difference between `querySelectorAll` and `getElementById` (or ByClass or ByTag) after a zillion iterations. A more accurate performance test for the inner workings of different libraries would be:

```javascript
// pre-define element
var x = document.getElementById('x');

// do inside loops:
vanillaHtml(x);
u(x).html();
jQuery(x).html();
Zepto(x).html();
```
 
With the above, I am pretty sure that u() would easily match other libraries, with results more accurately reflecting the performance of each library (which likely will not differ much). With the imminent jQuery exodus (even Bootstrap are abandoning jQuery) and mass-adoption of vanilla JS, many developers (like myself) are increasingly selective in terms of performance, and although essentially pointless, this itself might be a factor to consider for the future wellbeing of umbrella.

Essentially, inaccurate "performance tests" aside, umbrella is good as is. But just to emphasize some further points and ideas for the sake of this topic, I recently added the following selector shortcuts to my JS:

```javascript
_id = document.getElementById.bind(document);
_class = function(clazz, context){
	return Array.from((context || document).getElementsByClassName(clazz));
}
_tag = function(tag, context){
	return Array.from((context || document).getElementsByTagName(tag));
}
_query = function(query, context){
	return (context || document).querySelector(query);
}
_querya = function(query, context){
	return Array.from((context || document).querySelectorAll(query));
}
```

Now, in the case of umbrella, I will probably use it like this:

```javascript
u(_id('id'));
u(_class('myclass'));
u(_class('myclass', context));
u(_tag('span'));
u('#id > .myclass'); // needs querySelectorAll anyway
```

I guess I was hoping that u() kinda worked like this by default, but I see now it is unfeasible and would be prone to user-error. I am not sure how complex it would be to regex the u(selector) and identify strings that don't require `querySelectorAll()`, like `#id`, `.myclass` and `span`, but assuming it's regarded "not worth it" vs "benefits" (which I don't essentially disagree upon).

I know it's not feasible, but a nerdy non-regex solution for performance-freaks could have been:

```javascript
// u(selector, context = null, querySelector = true);
u('#id', null, false);
u('.classname', null, false);
u('span', null, false);
// forces getElementById(), getElementsByClassName() or getElementsByTagName()
```

Another nerdy option would be to create a wrapper function (for example `_u()`), that only accepts "non-queryish" single #ID, .class or tag selector, and passes on to `u()`. Such a function could easily be added by ourselves of course:

```javascript
_u('#id');
_u('.classname');
_u('span');
// Only uses getElementById(), getElementsByClassName() or getElementsByTagName(), depending on char[0].
```

Anyway, just food for thought ❤

**Comment by franciscop** [comment]
Oh actually [in a previous version Umbrella could be split to work like that](https://github.com/franciscop/umbrella/blob/2.10.2/src/plugins/select/select.js#L11), where you could add a new selector easily with Regex (pasting the example for the class selector):

```js
u.prototype.selectors[/^\.[\w\-]+$/] = function (param) {
  return document.getElementsByClassName(param.substring(1));
};
```

Umbrella is pretty much feature-complete, so I don't expect major changes to happen. If you are really worried about this performance bit, you could use the `2.x` version (which is a superset of `3.x` AFAIK, no new features were added in `3.x`) or copy/paste this code somewhere, effectively modifying the selector to do the Regexp from `2.x` while keeping the tighter size and removed features of 3.x:

```js
// [INTERNAL USE ONLY]
// Select the adecuate part from the context
u.prototype.select = function (parameter, context) {
  // Allow for spaces before or after
  parameter = parameter.replace(/^\s*/, '').replace(/\s*$/, '');

  if (context) {
    return this.select.byCss(parameter, context);
  }

  for (var key in this.selectors) {
    // Reusing it to save space
    context = key.split('/');
    if ((new RegExp(context[1], context[2])).test(parameter)) {
      return this.selectors[key](parameter);
    }
  }

  return this.select.byCss(parameter);
};

// Select some elements using a css Selector
u.prototype.select.byCss = function (parameter, context) {
  return (context || document).querySelectorAll(parameter);
};

// Allow for adding/removing regexes and parsing functions
// It stores a regex: function pair to process the parameter and context
u.prototype.selectors = {};

// Find some html nodes using an Id
u.prototype.selectors[/^\.[\w\-]+$/] = function (param) {
  return document.getElementsByClassName(param.substring(1));
};

// The tag nodes
u.prototype.selectors[/^\w+$/] = function (param) {
  return document.getElementsByTagName(param);
};

// Find some html nodes using an Id
u.prototype.selectors[/^\#[\w\-]+$/] = function (param) {
  return document.getElementById(param.substring(1));
};

// Create a new element for the DOM
u.prototype.selectors[/^</] = function (param) {
  return u().generate(param);
};
```

I do agree with your points, but those Regex had minor issues and were modified one by one to fix them, which became a pain point and a bug source. Why not just let the browser do that? So I removed them. If Umbrella's speed itself is really the bottleneck for someone, I'd bet that:
- they should be using raw, native JS because they want to juice the last drops of performance, and no library will work.
- they are doing something horribly wrong, like selecting the same element again inside a tight loop, or trashing the DOM in a loop, and again this is not really the library's concern.

Now if you found a single selector took something like 1ms-10ms, then that'd be a huge concern. But for everyday Javascript, I haven't found this limiting at all and no one has reported (yet) any performance issue on the wild (besides synthetic benchmarks).

**Comment by franciscop** [comment]
> On a side note, it's unfortunate how performance tests (like the one in this post) reflect negatively upon umbrella.

I'm very happy where Umbrella is so no worries 😄

Recently I am using React more and more, but when I want a good ol' bit of JS, I normally use Umbrella with no issue.

**Comment by mjau-mjau** [comment]
I already have my own selector methods to feed into `u()`, so I have no reason to downgrade to 2.0. As mentioned, I also agree that performance benefits are insignificant (even in extreme case scenarios). My only point was "performance benchmarks".

All good on my side thanks, and happy to be using the <3kb UmbrellaJS 👌
