### ISSUE TITLE
Importing using RequireJS

### ISSUE THREAD

**Issue by DevBonBon** [franciscop/umbrella#134]
Umbrella seems to always attach itself to the window, rather than returning a reference to use in the current context.
```
// This loads the library and it's reachable
require(['https://cdn.jsdelivr.net/npm/umbrellajs?noext'], () => {
  console.log(u)
});

require(['https://cdn.jsdelivr.net/npm/umbrellajs?noext'], (u) => {
  console.log(u) // u is undefined
});
```
Is there a limitation to the implementation, or is this actually unwanted behaviour?
The readme does have examples on umbrella returning a reference on request

**Comment by franciscop** [comment]
Neither? The expected behaviour is that it will define itself globally, but import/require were not considered heavily. There's a small export thingy that used to work with some bundlers:

https://github.com/franciscop/umbrella/blob/master/src/export.js

Feel free to do a PR if you want this functionality as long as it doesn't blow up the size :)
