### ISSUE TITLE
Broken documentation website

### ISSUE THREAD

**Issue by aishikaty** [franciscop/umbrella#85]
I've got this error at https://umbrellajs.com/documentation
```
Uncaught ReferenceError: u is not defined at documentation:1322
```

**Comment by bharatramnani94** [comment]
That's because https://umbrellajs.com/umbrella.min.js returns 404 (No file found).
It can be corrected by copying `umbrella.min.js` inside [/docs](https://github.com/franciscop/umbrella/tree/master/docs) directory of this repo, or including the CDN link on line 16 of [documentation.html.jade](https://github.com/franciscop/umbrella/blob/master/docs/documentation.html.jade).

**Comment by franciscop** [comment]
Oops, true, I recently moved it. However I'll be using `unpkg.com` as a CDN instead. Thanks for the heads up!
